/** All entities now carry a permanent `id` from creation (see questionEditorStore),
 * so there is no longer a separate draft/server-id distinction; these are thin
 * re-exports of the frozen QD-FB-2.1 model kept under their historical names to
 * minimize import churn across the wizard. */
export type {
  ResponseInteraction as InteractionDraft,
  ResponseInteraction,
  ResponseInteractionType as InteractionType,
  Selecting,
  Ordering,
  Relating,
  Completing,
  ShortInput,
  Essay,
  ArtifactSubmission,
  Marking,
  Choice,
  OrderingItem,
  RelatingElement,
  RelatingSet,
  CorrectRelation,
  CompletingGap,
  CompletingItem,
  TextInputGap,
  NumberInputGap,
  DateInputGap,
  DropTargetGap,
  TextCompletingItem,
  ImageCompletingItem,
  CompletingItemUsageLimit,
  Anchor,
  TextAnchor,
  RegionAnchor,
  ItemOrderPolicy,
  RelatingMappingType,
  ParticipationPolicy,
  EssayLengthUnit,
  MarkType,
} from '@/domain/qd/model'
